apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: k8s-learning-demo
data:
  APP_NAME: "My Kubernetes Lab"
  WELCOME_MESSAGE: "Frontend, Backend and PostgreSQL are running in Kubernetes"
  THEME_COLOR: "#7c5cff"
  API_URL: "http://localhost:30081"
  POSTGRES_DB: "demo"
  POSTGRES_USER: "demo"
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: k8s-learning-demo
type: Opaque
stringData:
  POSTGRES_PASSWORD: "demo_password"
  DATABASE_URL: "postgresql://demo:demo_password@database:5432/demo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-init
  namespace: k8s-learning-demo
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS visits (
      id BIGSERIAL PRIMARY KEY,
      source TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
